### ISSUE TITLE
support the new site for more content

### ISSUE THREAD

**Issue by eyadsibai** [mohssineAboutaj/akwam-cli#1]

**Comment by mohssineAboutaj** [comment]
@eyadsibai it was such as a joke, but i will try with other websites

**Comment by eyadsibai** [comment]
If you convert to python I would help in thr support

**Comment by mohssineAboutaj** [comment]
sorry i can't do that, because i'm a JS developer so it's not a good choice for me
you can do that if your level is good in python, the main trick on this project is the request that you will send to thier server to get the data, i believe it's exist on fetch.js (maybe)
